In [2]:
%pip install mlflow dvc

Collecting mlflow
  Using cached mlflow-3.17.0-py3-none-any.whl.metadata (50 kB)
Collecting dvc
  Using cached dvc-3.67.1-py3-none-any.whl.metadata (17 kB)
Collecting mlflow-skinny==3.17.0 (from mlflow)
  Using cached mlflow_skinny-3.17.0-py3-none-any.whl.metadata (51 kB)
Collecting mlflow-tracing==3.17.0 (from mlflow)
  Using cached mlflow_tracing-3.17.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (3.1.3)
Collecting aiohttp<4,>=3.7.0 (from mlflow)
  Using cached aiohttp-3.14.5-cp313-cp313-win_amd64.whl.metadata (8.5 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Using cached alembic-1.20.0-py3-none-any.whl.metadata (7.3 kB)
Collecting cryptography<51,>=43.0.0 (from mlflow)
  Using cached cryptography-50.0.2-cp311-abi3-win_amd64.whl.metadata (4.4 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: huey<4,>=2.5.4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (3.4.0)
Requirement already satisfied: matplotlib<4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: numpy<3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (2.4.6)
Requirement already satisfied: pandas<4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (3.0.5)
Requirement already satisfied: pyarrow<26,>=4.0.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (25.0.1)
Requirement already satisfied: scikit-learn<2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (1.9.0)
Requirement already satisfied: scipy<2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (1.18.0)
Collecting skops<1 (from mlflow)
  Using cached skops-0.16.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (2.1.4)
Requirement already satisfied: waitress<4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: anyio!=4.15.0,<5,>=3.6.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (4.14.2)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.17.0->mlflow)
  Using cached cachetools-7.2.1-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (8.4.2)
Requirement already satisfied: cloudpickle<4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.17.0->mlflow)
  Using cached databricks_sdk-0.151.0-py3-none-any.whl.metadata (44 kB)
Collecting fastapi<1 (from mlflow-skinny==3.17.0->mlflow)
  Using cached fastapi-0.143.0-py3-none-any.whl.metadata (26 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.17.0->mlflow)
  Using cached gitpython-3.2.0-py3-none-any.whl.metadata (13 kB)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.17.0->mlflow)
  Using cached importlib_metadata-9.0.1-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (1.45.1)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.17.0->mlflow)
  Using cached opentelemetry_proto-1.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.17.0->mlflow)
  Using cached opentelemetry_sdk-1.45.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (6.33.6)
Collecting pydantic<3,>=2.0.0 (from mlflow-skinny==3.17.0->mlflow)
  Using cached pydantic-2.14.1-py3-none-any.whl.metadata (133 kB)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (1.2.4)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (2.34.2)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (0.6.0)
Collecting starlette<2 (from mlflow-skinny==3.17.0->mlflow)
  Using cached starlette-1.7.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlflow-skinny==3.17.0->mlflow) (4.16.0)
Collecting uvicorn<1 (from mlflow-skinny==3.17.0->mlflow)
  Using cached uvicorn-0.54.0-py3-none-any.whl.metadata (6.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.4)
Collecting yarl<2.0,>=1.25.1 (from aiohttp<4,>=3.7.0->mlflow)
  Using cached yarl-1.25.1-cp313-cp313-win_amd64.whl.metadata (115 kB)
Requirement already satisfied: Mako in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.4.3)
Requirement already satisfied: idna>=2.8 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.17.0->mlflow) (3.18)
Requirement already satisfied: colorama in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.17.0->mlflow) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cryptography<51,>=43.0.0->mlflow) (2.1.1)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.17.0->mlflow)
  Using cached google_auth-2.61.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.17.0->mlflow) (2.7.0)
Requirement already satisfied: pywin32>=304 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from docker<8,>=4.0.0->mlflow) (312)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fastapi<1->mlflow-skinny==3.17.0->mlflow) (0.4.4)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.17.0->mlflow)
  Using cached annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: blinker>=1.9.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from Flask<4->mlflow) (3.1.8)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.17.0->mlflow)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.17.0->mlflow) (5.0.3)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.17.0->mlflow)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from graphene<4->mlflow) (3.2.13)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.17.0->mlflow) (4.1.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=9 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<4->mlflow) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<4->mlflow) (3.3.2)
Collecting opentelemetry-semantic-conventions==0.66b1 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.17.0->mlflow)
  Using cached opentelemetry_semantic_conventions-0.66b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: tzdata in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas<4->mlflow) (2026.3)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2.0.0->mlflow-skinny==3.17.0->mlflow)
  Using cached annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: pydantic-core==2.50.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.17.0->mlflow) (2.50.1)
Requirement already satisfied: six>=1.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.17.0->mlflow) (3.4.9)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.17.0->mlflow) (2026.7.22)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn<2->mlflow) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: h11>=0.8 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from uvicorn<1->mlflow-skinny==3.17.0->mlflow) (0.16.0)
Collecting celery (from dvc)
  Using cached celery-5.6.3-py3-none-any.whl.metadata (23 kB)
Collecting configobj>=5.0.9 (from dvc)
  Using cached configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting distro>=1.3 (from dvc)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting dpath<3,>=2.1.0 (from dvc)
  Using cached dpath-2.2.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: dulwich in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.2.17)
Collecting dvc-data<3.19.0,>=3.18.2 (from dvc)
  Using cached dvc_data-3.18.3-py3-none-any.whl.metadata (4.9 kB)
Collecting dvc-http>=2.29.0 (from dvc)
  Using cached dvc_http-2.32.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: dvc-objects in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.2.0)
Requirement already satisfied: dvc-render<2,>=1.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.0.2)
Collecting dvc-studio-client<1,>=0.21 (from dvc)
  Using cached dvc_studio_client-0.23.0-py3-none-any.whl.metadata (4.4 kB)
Collecting dvc-task<1,>=0.3.0 (from dvc)
  Using cached dvc_task-0.40.2-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: flatten-dict<1,>=0.4.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.5.0)
Collecting flufl.lock<10,>=8.1.0 (from dvc)
  Using cached flufl_lock-9.2.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: fsspec>=2024.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2026.9.0)
Requirement already satisfied: funcy>=1.14 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.1)
Requirement already satisfied: grandalf<1,>=0.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.8)
Collecting gto<2,>=1.6.0 (from dvc)
  Using cached gto-1.10.1-py3-none-any.whl.metadata (4.8 kB)
Collecting hydra-core>=1.1 (from dvc)
  Using cached hydra_core-1.3.7-py3-none-any.whl.metadata (5.7 kB)
Collecting iterative-telemetry>=0.0.7 (from dvc)
  Using cached iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting kombu (from dvc)
  Using cached kombu-5.6.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: networkx>=2.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.7)
Requirement already satisfied: omegaconf in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.3.1)
Requirement already satisfied: pathspec<2,>=0.10.3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.1.1)
Requirement already satisfied: platformdirs<5,>=3.1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.11.0)
Requirement already satisfied: psutil>=5.8 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (7.2.2)
Requirement already satisfied: pydot>=1.2.4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.0.1)
Requirement already satisfied: pygtrie>=2.3.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.6.2)
Requirement already satisfied: rich>=12 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (15.0.0)
Requirement already satisfied: ruamel.yaml>=0.17.11 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.19.1)
Collecting scmrepo<4,>=3.5.2 (from dvc)
  Using cached scmrepo-3.6.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: shortuuid>=0.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.0.13)
Requirement already satisfied: shtab<2,>=1.3.4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.12.1)
Requirement already satisfied: tabulate>=0.8.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.10.0)
Requirement already satisfied: tomlkit>=0.11.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.15.1)
Requirement already satisfied: tqdm<5,>=4.63.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.70.1)
Requirement already satisfied: voluptuous>=0.11.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.16.0)
Requirement already satisfied: zc.lockfile>=1.2.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.0)
Collecting dictdiffer>=0.8.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Using cached dictdiffer-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Collecting diskcache>=5.2.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting sqltrie<1,>=0.11.0 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Using cached sqltrie-0.11.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: orjson<4,>=3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.13.0)
Collecting billiard<5.0,>=4.2.1 (from celery->dvc)
  Using cached billiard-4.3.1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: vine<6.0,>=5.1.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (5.1.0)
Collecting click-didyoumean>=0.3.0 (from celery->dvc)
  Using cached click_didyoumean-0.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting click-repl>=0.2.0 (from celery->dvc)
  Using cached click_repl-0.4.1-py3-none-any.whl.metadata (3.7 kB)
Collecting click-plugins>=1.1.1 (from celery->dvc)
  Using cached click_plugins-1.1.1.2-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: tzlocal in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (5.4.4)
Collecting atpublic (from flufl.lock<10,>=8.1.0->dvc)
  Using cached atpublic-8.0.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: entrypoints in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (0.4)
Collecting pydantic-settings>=2 (from gto<2,>=1.6.0->dvc)
  Using cached pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\madhu\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pyasn1_modules\\rfc7508.py'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install dvc

Requirement already satisfied: dvc in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.67.1)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (26.1.0)
Requirement already satisfied: celery in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.6.3)
Requirement already satisfied: colorama>=0.3.9 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.4.6)
Requirement already satisfied: configobj>=5.0.9 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.0.9)
Requirement already satisfied: distro>=1.3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.9.0)
Requirement already satisfied: dpath<3,>=2.1.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.2.0)
Requirement already satisfied: dulwich in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.2.17)
Requirement already satisfied: dvc-data<3.19.0,>=3.18.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.18.3)
Requirement already satisfied: dvc-http>=2.29.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.32.0)
Requirement already satisfied: dvc-objects in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.2.0)
Requirement already satisfied: dvc-render<2,>=1.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.0.2)
Requirement already satisfied: dvc-studio-client<1,>=0.21 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.23.0)
Requirement already satisfied: dvc-task<1,>=0.3.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.40.2)
Requirement already satisfied: flatten-dict<1,>=0.4.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.5.0)
Requirement already satisfied: flufl.lock<10,>=8.1.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (9.2.0)
Requirement already satisfied: fsspec>=2024.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2026.9.0)
Requirement already satisfied: funcy>=1.14 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.1)
Requirement already satisfied: grandalf<1,>=0.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.8)
Requirement already satisfied: gto<2,>=1.6.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.10.1)
Requirement already satisfied: hydra-core>=1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.3.7)
Requirement already satisfied: iterative-telemetry>=0.0.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.0.10)
Requirement already satisfied: kombu in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.6.2)
Requirement already satisfied: networkx>=2.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.7)
Requirement already satisfied: omegaconf in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.3.1)
Requirement already satisfied: packaging>=19 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (26.2)
Requirement already satisfied: pathspec<2,>=0.10.3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.1.1)
Requirement already satisfied: platformdirs<5,>=3.1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.11.0)
Requirement already satisfied: psutil>=5.8 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (7.2.2)
Requirement already satisfied: pydot>=1.2.4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.0.1)
Requirement already satisfied: pygtrie>=2.3.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.6.2)
Requirement already satisfied: pyparsing>=3.0.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.3.2)
Requirement already satisfied: requests>=2.22 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.34.2)
Requirement already satisfied: rich>=12 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (15.0.0)
Requirement already satisfied: ruamel.yaml>=0.17.11 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.19.1)
Requirement already satisfied: scmrepo<4,>=3.5.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.6.2)
Requirement already satisfied: shortuuid>=0.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.0.13)
Requirement already satisfied: shtab<2,>=1.3.4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.12.1)
Requirement already satisfied: tabulate>=0.8.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.10.0)
Requirement already satisfied: tomlkit>=0.11.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.15.1)
Requirement already satisfied: tqdm<5,>=4.63.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.70.1)
Requirement already satisfied: voluptuous>=0.11.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.16.0)
Requirement already satisfied: zc.lockfile>=1.2.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.0)
Requirement already satisfied: dictdiffer>=0.8.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.10.0)
Requirement already satisfied: diskcache>=5.2.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (5.6.3)
Requirement already satisfied: sqltrie<1,>=0.11.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.11.3)
Requirement already satisfied: orjson<4,>=3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.13.0)
Requirement already satisfied: pywin32>=225 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-task<1,>=0.3.0->dvc) (312)
Requirement already satisfied: billiard<5.0,>=4.2.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (4.3.1)
Requirement already satisfied: vine<6.0,>=5.1.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (5.1.0)
Requirement already satisfied: click<9.0,>=8.1.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (8.4.2)
Requirement already satisfied: click-didyoumean>=0.3.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (0.3.1)
Requirement already satisfied: click-repl>=0.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (0.4.1)
Requirement already satisfied: click-plugins>=1.1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (1.1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (2.9.0.post0)
Requirement already satisfied: tzlocal in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (5.4.4)
Requirement already satisfied: atpublic in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from flufl.lock<10,>=8.1.0->dvc) (8.0.1)
Requirement already satisfied: entrypoints in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic>=2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (2.14.1)
Requirement already satisfied: pydantic-settings>=2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (2.15.0)
Requirement already satisfied: semver>=2.13.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (3.1.0)
Requirement already satisfied: amqp<6.0.0,>=5.1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kombu->dvc) (5.4.1)
Requirement already satisfied: tzdata>=2025.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kombu->dvc) (2026.3)
Requirement already satisfied: gitpython>3 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (3.2.0)
Requirement already satisfied: pygit2>=1.14.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (1.20.1)
Requirement already satisfied: asyncssh<3,>=2.13.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (2.24.1)
Requirement already satisfied: aiohttp-retry>=2.5.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (2.9.1)
Requirement already satisfied: cryptography>=48.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (50.0.2)
Requirement already satisfied: typing_extensions>=4.0.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (4.16.0)
Requirement already satisfied: urllib3>=2.2.2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dulwich->dvc) (2.7.0)
Requirement already satisfied: aiohttp in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (3.14.5)
Requirement already satisfied: prompt_toolkit>=3.0.36 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click-repl>=0.2.0->celery->dvc) (3.0.53)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cryptography>=48.0.1->asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (2.1.1)
Requirement already satisfied: pycparser in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cffi>=2.0.0->cryptography>=48.0.1->asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (3.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gitpython>3->scmrepo<4,>=3.5.2->dvc) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc) (5.0.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from hydra-core>=1.1->dvc) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from omegaconf->dvc) (6.0.3)
Requirement already satisfied: appdirs in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from iterative-telemetry>=0.0.7->dvc) (1.4.4)
Requirement already satisfied: filelock in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from iterative-telemetry>=0.0.7->dvc) (4.0.12)
Requirement already satisfied: wcwidth>=0.1.4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from prompt_toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.8.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.4.4)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic-settings>=2->gto<2,>=1.6.0->dvc) (1.2.4)
Requirement already satisfied: six>=1.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->celery->dvc) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.22->dvc) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.22->dvc) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.22->dvc) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12->dvc) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12->dvc) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: setuptools in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from zc.lockfile>=1.2.1->dvc) (84.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.25.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import mlflow
import dvc
import sklearn
import pandas
import joblib
import matplotlib

print("MLflow version:", mlflow.__version__)
print("Scikit-learn version:", sklearn.__version__)
print("All libraries imported successfully!")

MLflow version: 3.17.0
Scikit-learn version: 1.9.0
All libraries imported successfully!

In [4]:
%pip show dvc

Name: dvc
Version: 3.67.1
Summary: Git for data scientists - manage your code and data together
Home-page:
Author:
Author-email: Dmitry Petrov <dmitry@dvc.org>
License-Expression: Apache-2.0
Location: c:\Users\madhu\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires: attrs, celery, colorama, configobj, distro, dpath, dulwich, dvc-data, dvc-http, dvc-objects, dvc-render, dvc-studio-client, dvc-task, flatten-dict, flufl.lock, fsspec, funcy, grandalf, gto, hydra-core, iterative-telemetry, kombu, networkx, omegaconf, packaging, pathspec, platformdirs, psutil, pydot, pygtrie, pyparsing, requests, rich, ruamel.yaml, scmrepo, shortuuid, shtab, tabulate, tomlkit, tqdm, voluptuous, zc.lockfile
Required-by:
Note: you may need to restart the kernel to use updated packages.

# dataset generate

In [6]:
import os
import pandas as pd
from sklearn.datasets import load_breast_cancer

# Create project folders
os.makedirs("data", exist_ok=True)
os.makedirs("models", exist_ok=True)
os.makedirs("screenshots", exist_ok=True)

# Load dataset
dataset = load_breast_cancer(as_frame=True)

# Combine features and target
df = dataset.frame

# Save dataset
df.to_csv("data/dataset.csv", index=False)

print("Dataset created successfully!")
print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Dataset created successfully!
Dataset shape: (569, 31)

First 5 rows:

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

# : Train 3 models using MLflow

In [8]:
import os
import mlflow
import mlflow.sklearn
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Load dataset
df = pd.read_csv("data/dataset.csv")

X = df.drop(columns=["target"])
y = df["target"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Create models folder
os.makedirs("models", exist_ok=True)

# Configure MLflow experiment
mlflow.set_experiment("MLTrackPro_Classification")

experiments = [
    {
        "name": "Logistic_Regression",
        "model": make_pipeline(
            StandardScaler(),
            LogisticRegression(max_iter=2000, C=1.0)
        ),
        "params": {"model": "LogisticRegression", "C": 1.0}
    },
    {
        "name": "Random_Forest_50",
        "model": RandomForestClassifier(
            n_estimators=50, max_depth=10, random_state=42
        ),
        "params": {
            "model": "RandomForest",
            "n_estimators": 50,
            "max_depth": 10
        }
    },
    {
        "name": "SVM_RBF",
        "model": make_pipeline(
            StandardScaler(),
            SVC(C=1.0, kernel="rbf")
        ),
        "params": {
            "model": "SVC",
            "C": 1.0,
            "kernel": "rbf"
        }
    }
]

results = []

for exp in experiments:
    with mlflow.start_run(run_name=exp["name"]):

        model = exp["model"]
        model.fit(X_train, y_train)

        predictions = model.predict(X_test)

        accuracy = accuracy_score(y_test, predictions)
        precision = precision_score(y_test, predictions, zero_division=0)
        recall = recall_score(y_test, predictions, zero_division=0)
        f1 = f1_score(y_test, predictions, zero_division=0)

        # Log parameters
        mlflow.log_params(exp["params"])

        # Log metrics
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

        # Save model artifact in MLflow
        mlflow.sklearn.log_model(
            sk_model=model,
            name="model",
            serialization_format="pickle"
       )

        # Save model file for DVC versioning
        model_path = f"models/{exp['name']}.joblib"
        joblib.dump(model, model_path)

        results.append({
            "Experiment": exp["name"],
            "Accuracy": accuracy,
            "Precision": precision,
            "Recall": recall,
            "F1 Score": f1
        })

# Display experiment comparison
results_df = pd.DataFrame(results)
display(results_df.round(4))

print("All 3 experiments logged successfully!")
print("Trained model files saved in models/")

2026/10/12 20:40:20 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/10/12 20:40:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/10/12 20:40:32 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

            Experiment  Accuracy  Precision  Recall  F1 Score
0  Logistic_Regression    0.9825     0.9861  0.9861    0.9861
1     Random_Forest_50    0.9561     0.9589  0.9722    0.9655
2              SVM_RBF    0.9825     0.9861  0.9861    0.9861

All 3 experiments logged successfully!
Trained model files saved in models/

# 3 MLflow experiments successfully run

| Model               | Accuracy | F1 Score |
| ------------------- | -------: | -------: |
| Logistic Regression |   98.25% |   98.61% |
| Random Forest       |   95.61% |   96.55% |
| SVM (RBF)           |   98.25% |   98.61% |

# MLflow UI

In [9]:
import mlflow

print("Tracking URI:", mlflow.get_tracking_uri())
print("Experiment:", mlflow.get_experiment_by_name("MLTrackPro_Classification").name)

Tracking URI: sqlite:///C:/Users/madhu/OneDrive/Desktop/6%20month%20internship%20program/MLTrackPro/mlflow.db
Experiment: MLTrackPro_Classification

# DVC setup

In [10]:
import subprocess

result = subprocess.run(
    ["dvc", "init"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

ERROR: failed to initiate DVC - c:\Users\madhu\OneDrive\Desktop\6 month internship program\MLTrackPro is not tracked by any supported SCM tool (e.g. Git). Use `--no-scm` if you don't want to use any SCM or `--subdir` if initializing inside a subdirectory of a parent SCM repository.

# Git initialize

In [11]:
import subprocess

result = subprocess.run(
    ["git", "init"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Initialized empty Git repository in C:/Users/madhu/OneDrive/Desktop/6 month internship program/MLTrackPro/.git/

# DVC initialize

In [12]:
import subprocess

result = subprocess.run(
    ["dvc", "init"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/treeverse/dvc>

# Track the Dataset with DVC

In [13]:
import subprocess

result = subprocess.run(
    ["dvc", "add", "data/dataset.csv"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

To track the changes with git, run:

	git add 'data\dataset.csv.dvc' 'data\.gitignore'

To enable auto staging, run:

	dvc config core.autostage true

â ‹ Checking graph

# Track the Trained Models with DVC

In [14]:
import subprocess

result = subprocess.run(
    ["dvc", "add", "models/"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

To track the changes with git, run:

	git add .gitignore models.dvc

To enable auto staging, run:

	dvc config core.autostage true

â ‹ Checking graph

# Configure a Local DVC Remote

In [15]:
import os
import subprocess

os.makedirs("../MLTrackPro_DVC_Remote", exist_ok=True)

result = subprocess.run(
    ["dvc", "remote", "add", "-d", "localremote", "../MLTrackPro_DVC_Remote"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Setting 'localremote' as a default remote.

# Push the Dataset and Models to DVC Remote

In [16]:
import subprocess

result = subprocess.run(
    ["dvc", "push"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

5 files pushed

# Check DVC Status

In [17]:
import subprocess

result = subprocess.run(
    ["dvc", "status"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Data and pipelines are up to date.

# Stage and Commit Files to Git

In [18]:
import subprocess

commands = [
    ["git", "add", "."],
    ["git", "status", "--short"]
]

for command in commands:
    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )
    print("$", " ".join(command))
    print(result.stdout)
    print(result.stderr)

$ git add .

warning: in the working copy of 'mlruns/1/models/m-170215c59be04b4caaa4e0de49fa692f/artifacts/requirements.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mlruns/1/models/m-61f0b218e3194614a9d89368602da47e/artifacts/requirements.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mlruns/1/models/m-f2fad98b5c994600ae24d696e210fe1a/artifacts/requirements.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mlruns/1/models/m-f9f3eba2f11b4e23be9806f3569efd8d/artifacts/requirements.txt', LF will be replaced by CRLF the next time Git touches it

$ git status --short
A  .dvc/.gitignore
A  .dvc/config
A  .dvcignore
A  .gitignore
A  data/.gitignore
A  data/dataset.csv.dvc
A  experiment_tracking.ipynb
A  mlflow.db
A  mlruns/1/models/m-170215c59be04b4caaa4e0de49fa692f/artifacts/MLmodel
A  mlruns/1/models/m-170215c59be04b4caaa4e0de49fa692f/artifacts/conda.yaml
A  mlruns/1/models/m-170215c59be04b4caaa4e0de49fa692f/artifacts/model.skops
A  mlruns/1/models/m-170215c59be04b4caaa4e0de49fa692f/artifacts/python_env.yaml
A  mlruns/1/models/m-170215c59be04b4caaa4e0de49fa692f/artifacts/requirements.txt
A  mlruns/1/models/m-61f0b218e3194614a9d89368602da47e/artifacts/MLmodel
A  mlruns/1/models/m-61f0b218e3194614a9d89368602da47e/artifacts/conda.yaml
A  mlruns/1/models/m-61f0b218e3194614a9d89368602da47e/artifacts/model.pkl
A  mlruns/1/models/m-61f0b218e3194614a9d89368602da47e/artifacts/python_env.yaml
A  mlruns/1/models/m-61f0b218e3194614a9d89368602da47e/artifacts/requirements.txt
A  mlruns/1/models/m-f2fad98b5c994600ae24d696e210fe1a/artifacts/MLmodel
A  mlruns/1/models/m-f2fad98b5c994600ae24d696e210fe1a/artifacts/conda.yaml
A  mlruns/1/models/m-f2fad98b5c994600ae24d696e210fe1a/artifacts/model.pkl
A  mlruns/1/models/m-f2fad98b5c994600ae24d696e210fe1a/artifacts/python_env.yaml
A  mlruns/1/models/m-f2fad98b5c994600ae24d696e210fe1a/artifacts/requirements.txt
A  mlruns/1/models/m-f9f3eba2f11b4e23be9806f3569efd8d/artifacts/MLmodel
A  mlruns/1/models/m-f9f3eba2f11b4e23be9806f3569efd8d/artifacts/conda.yaml
A  mlruns/1/models/m-f9f3eba2f11b4e23be9806f3569efd8d/artifacts/model.pkl
A  mlruns/1/models/m-f9f3eba2f11b4e23be9806f3569efd8d/artifacts/python_env.yaml
A  mlruns/1/models/m-f9f3eba2f11b4e23be9806f3569efd8d/artifacts/requirements.txt
A  models.dvc
A  screenshots/run.png

| Task                                | Status     |
| ----------------------------------- | ---------- |
| Created 3 MLflow experiments        | ✅ Complete |
| Logged model parameters and metrics | ✅ Complete |
| Opened the MLflow UI                | ✅ Complete |
| Initialized Git and DVC             | ✅ Complete |
| Tracked the dataset with DVC        | ✅ Complete |
| Tracked trained models with DVC     | ✅ Complete |
| Configured a local DVC remote       | ✅ Complete |
| Pushed 5 files to the DVC remote    | ✅ Complete |
| Committed project files to Git      | ✅ Complete |
| Pushed the project to GitHub        | ✅ Complete |

In [19]:
import mlflow
import pandas as pd

# Retrieve the previous MLflow run
run_id = "0ef65e0a6a504df69a16800c866baee3"
client = mlflow.tracking.MlflowClient()
run = client.get_run(run_id)

# Display the logged parameters and metrics
print("Previous Experiment Parameters:")
print(run.data.params)

print("\nPrevious Experiment Metrics:")
print(run.data.metrics)

# Load the DVC-tracked dataset
df = pd.read_csv("data/dataset.csv")

print("\nDataset loaded successfully!")
print("Dataset shape:", df.shape)

Previous Experiment Parameters:
{'model': 'LogisticRegression', 'C': '1.0'}

Previous Experiment Metrics:
{'accuracy': 0.9824561403508771, 'precision': 0.9861111111111112, 'recall': 0.9861111111111112, 'f1_score': 0.9861111111111112}

Dataset loaded successfully!
Dataset shape: (569, 31)

# Reproduce Logistic Regression

In [20]:
import mlflow
import mlflow.sklearn
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Retrieve parameters from the original MLflow run
run_id = "0ef65e0a6a504df69a16800c866baee3"
client = mlflow.tracking.MlflowClient()
original_run = client.get_run(run_id)

C_value = float(original_run.data.params["C"])

# Load the DVC-tracked dataset
df = pd.read_csv("data/dataset.csv")
X = df.drop(columns=["target"])
y = df["target"]

# Recreate the original train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train using the logged parameter
model = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=2000, C=C_value)
)

model.fit(X_train, y_train)
predictions = model.predict(X_test)

# Calculate evaluation metrics
metrics = {
    "accuracy": accuracy_score(y_test, predictions),
    "precision": precision_score(y_test, predictions, zero_division=0),
    "recall": recall_score(y_test, predictions, zero_division=0),
    "f1_score": f1_score(y_test, predictions, zero_division=0)
}

# Log the reproduced experiment as a new MLflow run
with mlflow.start_run(run_name="Logistic_Regression_Reproduced"):
    mlflow.log_param("model", "LogisticRegression")
    mlflow.log_param("C", C_value)
    mlflow.log_param("reproduced_from_run", run_id)
    mlflow.log_metrics(metrics)

    mlflow.sklearn.log_model(
        sk_model=model,
        name="model",
        serialization_format="pickle"
    )

print("Original run ID:", run_id)
print("Reproduced parameters:", {"C": C_value})
print("\nReproduced metrics:")

for name, value in metrics.items():
    print(f"{name}: {value:.4f}")

print("\nExperiment reproduction completed successfully!")

2026/10/12 22:16:07 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Original run ID: 0ef65e0a6a504df69a16800c866baee3
Reproduced parameters: {'C': 1.0}

Reproduced metrics:
accuracy: 0.9825
precision: 0.9861
recall: 0.9861
f1_score: 0.9861

Experiment reproduction completed successfully!

In [ ]:
import mlflow
import pandas as pd

# Retrieve the previous MLflow run
run_id = "0ef65e0a6a504df69a16800c866baee3"
client = mlflow.tracking.MlflowClient()
run = client.get_run(run_id)

# Display the logged parameters and metrics
print("Previous Experiment Parameters:")
print(run.data.params)

print("\nPrevious Experiment Metrics:")
print(run.data.metrics)

# Load the DVC-tracked dataset
df = pd.read_csv("data/dataset.csv")

print("\nDataset loaded successfully!")
print("Dataset shape:", df.shape)

Previous Experiment Parameters:
{'model': 'LogisticRegression', 'C': '1.0'}

Previous Experiment Metrics:
{'accuracy': 0.9824561403508771, 'precision': 0.9861111111111112, 'recall': 0.9861111111111112, 'f1_score': 0.9861111111111112}

Dataset loaded successfully!
Dataset shape: (569, 31)